# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Jennifer Washburn # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Adventure Seeking Front-End Web Developer</h1>
     <p>I'm a kickass developer specializing in AngularJS and UI Bootstrap.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: "jjw244@utexas.edu" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "https://www.facebook.com/jennibear"
  flickr:
  github: "jjw244" # github profile name, e.g. "madebymunsters"
  google_plus: "u/0/+JenniferWashburn"
  instagram:
  linkedin:  "https://www.linkedin.com/in/jjw244/" # Full URL
  pinterest: "jennibear"
  reddit:
  soundcloud:
  stack_exchange: "http://stackexchange.com/users/10502956/user120077"  # Full URL
  steam:
  tumblr: "deliciousdelicaciestx"
  twitter:
  wordpress: "deliciousdelicaciestx.com"
  youtube:

  # Scripts
  google_analytics: "UA-9620389-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow me on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
